swagger: "2.0"
info:
  description: "Documentation for Node.js Quickstart."
  version: "1"
  title: "Node.js Quickstart"
basePath: "/v1"
schemes:
- "http"
- "https"
paths:
  /auth/signup:
    post:
      tags:
      - "Auth"
      summary: "Signup new user"
      description: "create new user"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
        - in: body
          name: user
          description: The user to create.
          schema:
            type: object
            required:
              - email
              - password
              - password_repeat
            properties:
              email:
                type: string
              password:
                type: string
              password_repeat:
                type: string
              firstname:
                type: string
              lastname:
                type: string
      responses:
        200:
          description: Authentication data
          schema:
            type: object
            properties:
              id:
                type: string
                description: UUID of newly created user
  /auth/signin:
    post:
      tags:
      - "Auth"
      summary: "Signin existing user"
      description: "login registered user"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
        - in: body
          name: user
          description: The user to create.
          schema:
            type: object
            required:
              - username
              - password
            properties:
              username:
                type: string
              password:
                type: string
              role:
                type: number
      responses:
        200:
          description: Authentication data
          schema:
            type: object
            properties:
              userId:
                type: string
                description: UUID of user
              authToken:
                type: string
                description: Generated token to check authentication status
  /auth/verify/{token}:
    post:
      tags:
      - "Auth"
      summary: "Verify registered user"
      description: "Verify registered user"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
        - in: path
          name: token
          type: string
          required: true
      responses:
        200:
          description: Authentication data
          schema:
            type: object
            properties:
              status:
                type: string
                description: return status 'verified'