version: "3"

services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./db_data/data:/var/lib/postgresql/data # add additional subdirectory, so docker build can work correctly

  adminer:
    image: adminer
    restart: always
    ports: 
      - ${ADMINER_PORT}:8080
    environment:
      - ADMINER_DEFAULT_SERVER=db
    depends_on: 
      - db

  backend:
    build: ../backend
    restart: always
    ports: 
      - ${EXTERNAL_BACKEND_APP_PORT}:${BACKEND_APP_PORT}
    environment:
      - APP_PORT=${BACKEND_APP_PORT}
      - API_VERSION=${API_VERSION}
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on: 
      - db

  frontend:
    build: ../frontend
    restart: always
    ports: 
      - ${EXTERNAL_FRONTEND_APP_PORT}:${NGINX_PORT}
    environment:
      - ENV_TYPE=${ENV_TYPE}
      - API_BASE_URL=${API_BASE_URL}
      - COOKIE_USER_ID_NAME=${COOKIE_USER_ID_NAME}
      - COOKIE_AUTH_TOKEN_NAME=${COOKIE_AUTH_TOKEN_NAME}



      DB_HOST=localhost
DB_USERNAME=user
DB_PASSWORD=password
DB_NAME=backend
DB_PORT=21444
BACKEND_APP_PORT=3000
FRONTEND_APP_PORT=3000
API_VERSION=v1
EXTERNAL_BACKEND_APP_PORT=21555
EXTERNAL_FRONTEND_APP_PORT=21666
NGINX_PORT=80
EXTERNAL_FRONTEND_APP_PORT=18576
ENV_TYPE=docker
API_BASE_URL=http://localhost:21555/v1
COOKIE_USER_ID_NAME=userId
COOKIE_AUTH_TOKEN_NAME=accessToken
ADMINER_PORT=22444