version: "3"

services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - 21445:5432
    environment:
      - POSTGRES_DB=backend
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - ./db_data/data:/var/lib/postgresql/data # add additional subdirectory, so docker build can work correctly

  adminer:
    image: adminer
    restart: always
    ports: 
      - 22445:8080
    environment:
      - ADMINER_DEFAULT_SERVER=db
    depends_on: 
      - db

  backend:
    build: ../backend
    restart: always
    ports: 
      - 21556:3000
    environment:
      - APP_PORT=3000
      - API_VERSION=v1
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=backend
      - DB_USERNAME=user
      - DB_PASSWORD=password
    depends_on: 
      - db

  frontend:
    build: ../frontend
    restart: always
    ports: 
      - 18577:80
    environment:
      - ENV_TYPE=docker
      - API_BASE_URL=http://localhost:21555/v1
      - COOKIE_USER_ID_NAME=userId
      - COOKIE_AUTH_TOKEN_NAME=accessToken