version: "3"

services:
  db:
    image: postgres:latest
    ports:
      - 21445:5432
    environment:
      - POSTGRES_DB=backend
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - ./db_data:/var/lib/postgresql/data
    deploy:
      replicas: 2

  adminer:
    image: adminer
    ports: 
      - 22445:8080
    environment:
      - ADMINER_DEFAULT_SERVER=db
    depends_on: 
      - db

  backend:
    image: dgaydukov/backend
    ports: 
      - 21556:3000
    environment:
      - APP_PORT=3000
      - API_VERSION=v1
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=backend
      - DB_USERNAME=user
      - DB_PASSWORD=password
    deploy:
      replicas: 2
    depends_on: 
      - db

  frontend:
    image: dgaydukov/frontend
    ports: 
      - 18577:80
    environment:
      - ENV_TYPE=swarm
      - API_BASE_URL=http://localhost:21556/v1
      - COOKIE_USER_ID_NAME=userId
      - COOKIE_AUTH_TOKEN_NAME=accessToken
    deploy:
      replicas: 3