version: "3"

services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./db_data/data:/var/lib/postgresql/data # add additional subdirectory, so docker build can work correctly

  adminer:
    image: adminer
    restart: always
    ports: 
      - ${ADMINER_PORT}:8080
    environment:
      - ADMINER_DEFAULT_SERVER=db
    depends_on: 
      - db

  # backend:
  #   build: .
  #   restart: always
  #   ports: 
  #     - ${COMPOSE_APP_PORT}:${APP_PORT}
  #   environment:
  #     - APP_PORT=${APP_PORT}
  #     - DB_HOST=db
  #     - DB_PORT=5432
  #     - DB_NAME=${DB_NAME}
  #     - DB_USERNAME=${DB_USERNAME}
  #     - DB_PASSWORD=${DB_PASSWORD}
  #   depends_on: 
  #     - db

  # frontend:
  #   build: .
  #   restart: always
  #   ports: 
  #     - ${COMPOSE_APP_PORT}:${APP_PORT}
  #   environment:
  #     - APP_PORT=${APP_PORT}
  #     - DB_HOST=db
  #     - DB_PORT=5432
  #     - DB_NAME=${DB_NAME}
  #     - DB_USERNAME=${DB_USERNAME}
  #     - DB_PASSWORD=${DB_PASSWORD}
  #   depends_on: 
  #     - backend
