
# backend deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: dgaydukov/backend
        ports:
        - containerPort: 80
        env:
        - name: APP_PORT
          value: "3000"
        - name: API_VERSION
          value: "v1"
        - name: DB_HOST
          value: "db"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "backend"
        - name: DB_USERNAME
          value: "user"
        - name: DB_PASSWORD
          value: "password"

# backend service
apiVersion: v1
kind: Service
metadata:
  name: backend-deployment
  labels:
    run: backend-deployment
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: backend-deployment

# frontend deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: dgaydukov/frontend
        ports:
        - containerPort: 80
        env:
        - name: ENV_TYPE
          value: "kubernetes"
        - name: API_BASE_URL
          value: "http://localhost:21556/v1"
        - name: COOKIE_USER_ID_NAME
          value: "userId"
        - name: COOKIE_AUTH_TOKEN_NAME
          value: "accessToken"

# frontend service
apiVersion: v1
kind: Service
metadata:
  name: frontend-deployment
  labels:
    run: frontend-deployment
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: frontend-deployment